"""empty message

Revision ID: 1756e4921d0
Revises: 23c82d0456d
Create Date: 2015-12-04 02:05:01.878825

"""

# revision identifiers, used by Alembic.
revision = '1756e4921d0'
down_revision = '23c82d0456d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_author_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'author')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_author_fkey', 'posts', 'users', ['author'], ['id'])
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
