"""empty message

Revision ID: 23c82d0456d
Revises: None
Create Date: 2015-12-04 01:51:49.785561

"""

# revision identifiers, used by Alembic.
revision = '23c82d0456d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pw', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author')
    op.drop_table('users')
    ### end Alembic commands ###
